### ISSUE TITLE
请问Sparse格式的数据怎么直接读取？

### ISSUE THREAD

**Issue by playchao** [chenghuige/hasky#1]
我看你代码里面都是把下面格式的数据：
「0 128:51 129:159 130:253 131:159 132:50」
处理成SparseTensor导出文件，然后再读取

这里是否可以直接读取  「0 128:51 129:159 130:253 131:159 132:50」 这个格式的数据呢？

**Comment by chenghuige** [comment]
本身就是sparse格式的数据 处理成SparseTensor是合理的啊
