### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by fword** [chenghuige/hasky#3]
1，util里的list_file返回的是不是绝对路径，string_input_producer能找到位置？
2，fix_sequence的作用是什么，为什么不shuffle_batch了

**Comment by chenghuige** [comment]
1.list_file返回的是绝对路径，作为string_input_producer的输入是绝对路径的list
2. fix_sequence是希望每次运行 读取顺序是一致的  这块儿我也没有太仔细研究 可能不准确 一般情况下也不是那么有必要使用， 大部分情况还是希望尽可能多的随机性

**Comment by fword** [comment]
def list_files(input):
  if os.path.isdir(input):
    return os.listdir(input)
  elif os.path.isfile(input):
    return [input]
  else:
    return glob.glob(input)
你看这个实现，我输入给一个文件夹的话，第一个if，就返回一个文件名的名字列表，不会给出绝对路径的啊

**Comment by chenghuige** [comment]
@fword 嗯。。 确实 没测试到这个地方，建议你直接外部获取好绝对路径的list输入 比较好
我应用过程中用到的是glob 那个是返回绝对路径

**Comment by chenghuige** [comment]
@fword  you can modify the code a bit by using
return [os.path.join(input, f) for f in os.listdir(input)] 
I have updated the code also.
