### ISSUE TITLE
slim.mlp "tf.get_variable_scope().reuse_variables()

### ISSUE THREAD

**Issue by hitfad** [chenghuige/hasky#5]
i have question about hasky/deepiu/image_caption/algos/discriminant_trainer.py line:148

when i not use "tf.get_variable_scope().reuse_variables()", it run well, it seems slim.mlp donot use tf.get_variable to create variable?

**Comment by chenghuige** [comment]
Well @hitfad  do you use  tf version 1.2.0-rc0 ? Currently I can not reproduce your problem. 
reuse variable so neg part share the variable of pos part. 
You can find melt.slim.mlp at hasky\util\melt\slim\layers.py it's just a wrapper of tf.slim.fully_connected and tf.slim.linear so internal code all use tf.get_variable
