### ISSUE TITLE
sequence_loss bug?

### ISSUE THREAD

**Issue by hitfad** [chenghuige/hasky#6]
def sequence_loss(self, sequence, 
                    initial_state=None, attention_states=None, 
                    input=None,
                    input_text=None,
                    exact_prob=False, exact_loss=False,
                    emb=None):

 neg_loss = self.decoder.sequence_loss(image_emb, neg_text_i, exact_loss=exact_loss)

is this a bug?

**Comment by chenghuige** [comment]
well, should be seqeuence_loss(neg_text_i, state, input=image_emb) like this
