### ISSUE TITLE
read hdfs train data

### ISSUE THREAD

**Issue by hitfad** [chenghuige/hasky#7]
hi,i saw you have prepare hdfs train data,but how can you feed into string_input_producer? i can see your list file is like this ,it cannot generate hdfs address for shuffle_and decode.py
 
def list_files(input):
  if os.path.isdir(input):
    return [os.path.join(input, f) for f in os.listdir(input)]
  elif os.path.isfile(input):
    return [input]
  else:
    return glob.glob(input)

**Comment by chenghuige** [comment]
you can use something like pyhdfs to list file in hdfs dir, and then path list of hdfs files paths to string_input_producer
